---
site_name: TrueLayer2Firefly
site_url: https://erwindouna.github.io/truelayer2firefly/
repo_url: https://github.com/erwindouna/truelayer2firefly

theme:
  name: material
  logo: assets/t2f.png
  favicon: assets/favicon.png
  palette:
    scheme: default
    primary: green
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.suggest
    - navigation.search.share
    -
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/erwindouna
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/erwindouna/

copyright: Copyright © 2025 Erwin Douna
